services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.dev
    environment:
      DATABASE_URL: postgresql://postgres.bmumcurtyjxqdrmnzptq:M8f9kmvSw03PrQba@aws-1-eu-west-2.pooler.supabase.com:6543/postgres?pgbouncer=true
      INNGEST_BASE_URL: http://inngest:8288
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      API_URL: http://backend:3000
      NEXT_PUBLIC_API_URL: http://localhost:3000
    depends_on:
      - backend

  inngest:
    image: inngest/inngest:latest
    ports:
      - "8288:8288"
    command: inngest dev -u http://backend:3000/api/inngest --host 0.0.0.0
    depends_on:
      - backend

volumes:
  pgdata:
